AWSTemplateFormatVersion: '2010-09-09'
Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: json-metadata-source-bucket

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseInput:
        Name: json_metadata_db

  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GlueCrawlerRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueCrawlerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                Resource: "*"
              - Effect: Allow
                Action:
                  - glue:CreateTable
                  - glue:GetTable
                  - glue:GetDatabase
                Resource: "*"

  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: JsonMetadataCrawler
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
          - Path: !Sub "s3://${S3Bucket}/"
      TablePrefix: json_
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: JsonMetadataTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GlueJobRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueJobPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - dynamodb:PutItem
                Resource: "*"

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: JsonMetadataToDynamoDB
      Role: !GetAtt GlueJobRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${S3Bucket}/scripts/json_to_dynamodb.py"
        PythonVersion: 3
      DefaultArguments:
        "--TempDir": !Sub "s3://${S3Bucket}/temp/"
        "--job-language": "python"